# Generated by Django 4.0.5 on 2022-07-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_followerscount_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerscount',
            name='profileImg',
        ),
    ]
